#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

branch_name=$(git symbolic-ref --short HEAD)

# Допустимые типы веток
pattern='^(feature|bugfix|hotfix|chore|refactor|test)/IT-[0-9]+$'

if ! echo "$branch_name" | grep -qE "$pattern"; 
then
  echo "❌ Название ветки '$branch_name' не соответствует шаблону."
  echo "\
==========================

Придерживайтесь формата: 
<тип>/IT-<номер>

ПРИМЕР:
feature/IT-5

Типы:
- feature: новая функциональность
- bugfix: исправление ошибки
- hotfix: срочное исправление
- chore: обслуживание проекта
- refactor: рефакторинг без изменения поведения
- test: добавление или изменение тестов    

==========================
" 
  exit 1
fi

echo "✅ Ветка '$branch_name' соответствует шаблону"

