#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

commit_msg_file=$1
commit_msg=$(cat "$commit_msg_file")

pattern='^(feat|fix|hotfix|chore|refactor|test|docs|style|ci)\(IT-[0-9]+\): .+'

if ! echo "$commit_msg" | grep -qE "$pattern"; 
then
echo "❌ Название коммита '$commit_msg' не соответствует шаблону."
echo "\
==========================

ПРИМЕР КОММИТА:

feat(IT-45): add routing

Типы:
- feat: новая функциональность
- fix: исправление ошибки
- hotfix: срочное исправление
- chore: обслуживание, не влияющие на код приложения
- refactor: рефакторинг без изменения поведения
- test: добавление/изменение тестов
- docs: работа с документацией
- style: изменения в коде, не влияющие на поведение
- ci: настройка CI/CD

==========================
" 
  exit 1
fi

echo "✅ Коммит '$commit_msg' соответствует шаблону"
