name: Build and Deploy to Kubernetes

on:
  push:
    branches:
      - main

env:
  ENV_TYPE: production
  PORT: 3891
  NAMESPACE: justmyshots-ru
  REGISTRY_HOSTNAME: backinct
  PROJECT: main-front
  # Добавляем имя деплоймента в переменные
  DEPLOYMENT_NAME: main-front-deployment  # Замените на ваше реальное имя деплоймента

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set image name
        run: |
          echo "IMAGE_NAME=${{ github.run_number }}_${{ env.ENV_TYPE }}_${{ github.sha }}" >> $GITHUB_ENV
          echo "DOCKER_IMAGE=${{ env.REGISTRY_HOSTNAME }}/${{ env.PROJECT }}:${{ env.IMAGE_NAME }}" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          docker build \
            --build-arg NEXT_PUBLIC_RECAPTCHA_SITE_KEY=${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }} \
            -t $DOCKER_IMAGE .
          docker push $DOCKER_IMAGE

      # ========== НАЧАЛО ДОБАВЛЕННОГО КОДА ==========
      - name: Install kubectl and yq
        run: |
          sudo apt-get update
          sudo apt-get install -y kubectl
          sudo snap install yq

      - name: Configure Kubernetes access
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
        run: |
          mkdir -p ~/.kube
          echo "$KUBE_CONFIG" > ~/.kube/config
          kubectl config use-context default

      - name: Update Kubernetes deployment
        run: |
          # Скачайте текущий deployment
          kubectl get deployment/${{ env.DEPLOYMENT_NAME }} -n ${{ env.NAMESPACE }} -o yaml > deployment.yaml
          
          # Добавьте переменные окружения
          yq e '.spec.template.spec.containers[0].env += [
            {"name": "NEXT_PUBLIC_RECAPTCHA_SITE_KEY", "value": "${{ secrets.NEXT_PUBLIC_RECAPTCHA_SITE_KEY }}"}
          ]' -i deployment.yaml
          
          # Обновите образ
          yq e ".spec.template.spec.containers[0].image = \"$DOCKER_IMAGE\"" -i deployment.yaml
          
          # Примените изменения
          kubectl apply -f deployment.yaml
          
          # Рестарт деплоймента
          kubectl rollout restart deployment/${{ env.DEPLOYMENT_NAME }} -n ${{ env.NAMESPACE }}
      # ========== КОНЕЦ ДОБАВЛЕННОГО КОДА ==========